/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package prapertemuan10;

/**
 *
 * @author U53R
 */
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;


public class NoteStis2 extends javax.swing.JFrame {

    /**
     * Creates new form NoteStis2
     */
    Integer charCount;
    Integer countConsonant;
    Integer countVocal;
    Integer jumlahBaris;
    private JFileChooser fileChooser = new JFileChooser();

    public NoteStis2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        prosesButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        saveProsesButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jumKarakterTextField = new javax.swing.JTextField();
        jumBarisTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        vokalTextField = new javax.swing.JTextField();
        konsonanTextField = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        filejMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 153));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        textArea.setBackground(new java.awt.Color(0, 0, 51));
        textArea.setColumns(20);
        textArea.setForeground(new java.awt.Color(255, 255, 255));
        textArea.setRows(5);
        jScrollPane1.setViewportView(textArea);

        prosesButton.setBackground(new java.awt.Color(51, 51, 51));
        prosesButton.setForeground(new java.awt.Color(255, 255, 255));
        prosesButton.setText("Proses Text");
        prosesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prosesButtonActionPerformed(evt);
            }
        });

        clearButton.setBackground(new java.awt.Color(51, 51, 51));
        clearButton.setForeground(new java.awt.Color(255, 255, 255));
        clearButton.setText("Clear Text Area");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        saveProsesButton.setBackground(new java.awt.Color(51, 51, 51));
        saveProsesButton.setForeground(new java.awt.Color(255, 255, 255));
        saveProsesButton.setText(" Save Proses Text (*.txt)");
        saveProsesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveProsesButtonActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Jumlah Karakter (diluar spasi) :");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Jumlah Baris :");

        jumKarakterTextField.setBackground(new java.awt.Color(0, 0, 51));
        jumKarakterTextField.setForeground(new java.awt.Color(255, 255, 255));
        jumKarakterTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumKarakterTextFieldActionPerformed(evt);
            }
        });

        jumBarisTextField.setBackground(new java.awt.Color(0, 0, 51));
        jumBarisTextField.setForeground(new java.awt.Color(255, 255, 255));
        jumBarisTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumBarisTextFieldActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Jumlah Huruf Konsonan :");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Jumlah Huruf Vokal :");

        vokalTextField.setBackground(new java.awt.Color(0, 0, 51));
        vokalTextField.setForeground(new java.awt.Color(255, 255, 255));
        vokalTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vokalTextFieldActionPerformed(evt);
            }
        });

        konsonanTextField.setBackground(new java.awt.Color(0, 0, 51));
        konsonanTextField.setForeground(new java.awt.Color(255, 255, 255));
        konsonanTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                konsonanTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(saveProsesButton)
                .addGap(34, 34, 34))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(11, 11, 11)
                            .addComponent(prosesButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jumKarakterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jumBarisTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(38, 38, 38)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(vokalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(konsonanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addContainerGap(28, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(saveProsesButton)
                .addContainerGap(138, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(216, 216, 216)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(prosesButton)
                        .addComponent(clearButton))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jumKarakterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(vokalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(22, 22, 22)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jumBarisTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(konsonanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(32, Short.MAX_VALUE)))
        );

        jMenuBar1.setForeground(new java.awt.Color(51, 51, 51));

        filejMenu.setBackground(new java.awt.Color(51, 51, 51));
        filejMenu.setForeground(new java.awt.Color(255, 255, 255));
        filejMenu.setText("File");

        openMenuItem.setBackground(new java.awt.Color(51, 51, 51));
        openMenuItem.setText("Open (*.txt)");
        openMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuItemActionPerformed(evt);
            }
        });
        filejMenu.add(openMenuItem);

        saveMenuItem.setText("Save (*.txt)");
        saveMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMenuItemActionPerformed(evt);
            }
        });
        filejMenu.add(saveMenuItem);

        jMenuBar1.add(filejMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void openFile() {
        int returnVal = fileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            try (BufferedReader reader = new BufferedReader(new FileReader(file))) {
                String line;
                StringBuilder text = new StringBuilder();
                while ((line = reader.readLine()) != null) {
                    text.append(line).append("\n");
                }
                textArea.setText(text.toString());
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
    }

    private void saveFile() {
        int returnValue = fileChooser.showOpenDialog(this);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            String filePath = file.getAbsolutePath();
            if (!filePath.endsWith(".txt")) {
                filePath += ".txt";
            }
            try {
                BufferedWriter writer = new BufferedWriter(new FileWriter(filePath));
                writer.write(textArea.getText());
                JOptionPane.showMessageDialog(null,"Save File Succes");
                writer.close();
            } catch (IOException e) {
                JOptionPane.showMessageDialog(null,"Save File Failed");
                e.printStackTrace();
            }
        }
    }

    private void saveTextProcess() {
        int returnValue = fileChooser.showOpenDialog(this);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            String filePath = file.getAbsolutePath();
            if (!filePath.endsWith(".txt")) {
                filePath += ".txt";
            }
            try (BufferedWriter writer = new BufferedWriter(new FileWriter(filePath))) {
                writer.write("Hasil proses text: ");
                writer.newLine();
                writer.write("Jumlah Karakter (diluar spasi): " + jumKarakterTextField.getText());
                writer.newLine();
                writer.write("Jumlah baris: " + jumBarisTextField.getText());
                writer.newLine();
                writer.write("Jumlah Huruf Vokal: " + vokalTextField.getText());
                writer.newLine();
                writer.write("Jumlah Huruf Konsonan: " + konsonanTextField.getText());
                JOptionPane.showMessageDialog(null, "Save Process File Succes");
            } catch (IOException e) {
                JOptionPane.showMessageDialog(null, "Save Process File Failed");
                e.printStackTrace();
            }
        }
    }
    private void saveMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMenuItemActionPerformed
        saveFile();
    }//GEN-LAST:event_saveMenuItemActionPerformed

    private void prosesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prosesButtonActionPerformed
        // TODO add your handling code here:
        String fullText = textArea.getText().replace(" ", "");

        // Split the text into lines and initialize counters
        String[] lineText = fullText.split("\n");
        jumlahBaris = 0; charCount = 0;
        jumlahBaris = lineText.length;

        // Loop through each line and count characters
        for (String textLine : lineText) {
            charCount += textLine.length();
        }

        // Update the text fields with the number of lines and characters
        jumBarisTextField.setText(jumlahBaris.toString());
        jumKarakterTextField.setText(charCount.toString());

        // Initialize consonant and vowel counters and convert the text to lowercase
        countConsonant = 0; countVocal = 0;
        String lowercaseText = fullText.toLowerCase();

        // Loop through each character in the lowercase text
        for (int i = 0; i < lowercaseText.length(); i++) {
            char letter = lowercaseText.charAt(i);

            // If the character is a letter, check if it's a consonant or vowel
            if (letter >= 'a' && letter <= 'z') {
                if (letter != 'a' && letter != 'i' && letter != 'u' && letter != 'e' && letter != '0') {
                    countConsonant++;
                } else {
                    countVocal++;
                }
            }
        }

        // Update the text fields with the number of consonants and vowels
        konsonanTextField.setText(countConsonant.toString());
        vokalTextField.setText(countVocal.toString());
    }//GEN-LAST:event_prosesButtonActionPerformed

    private void saveProsesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveProsesButtonActionPerformed
        // TODO add your handling code here:
        saveTextProcess();
    }//GEN-LAST:event_saveProsesButtonActionPerformed

    private void jumKarakterTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumKarakterTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jumKarakterTextFieldActionPerformed

    private void vokalTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vokalTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vokalTextFieldActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // TODO add your handling code here:
            // Clear the text area and reset all counters
        textArea.setText("");
        countConsonant = 0;
        countVocal = 0;
        jumlahBaris = 0;
        charCount = 0;
        jumBarisTextField.setText("0");
        konsonanTextField.setText("0");
        vokalTextField.setText("0");
        jumKarakterTextField.setText("0");
    }//GEN-LAST:event_clearButtonActionPerformed

    private void konsonanTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_konsonanTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_konsonanTextFieldActionPerformed

    private void jumBarisTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumBarisTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jumBarisTextFieldActionPerformed

    private void openMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuItemActionPerformed
        // TODO add your handling code here:
        openFile();
    }//GEN-LAST:event_openMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NoteStis2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NoteStis2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NoteStis2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NoteStis2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NoteStis2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearButton;
    private javax.swing.JMenu filejMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jumBarisTextField;
    private javax.swing.JTextField jumKarakterTextField;
    private javax.swing.JTextField konsonanTextField;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JButton prosesButton;
    private javax.swing.JMenuItem saveMenuItem;
    private javax.swing.JButton saveProsesButton;
    private javax.swing.JTextArea textArea;
    private javax.swing.JTextField vokalTextField;
    // End of variables declaration//GEN-END:variables
}
