/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package prapertemuan11;

/**
 *
 * @author U53R
 */
public class TestFrame extends javax.swing.JPanel {

    /**
     * Creates new form TestFrame
     */
    public TestFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();

        jLabel1.setText("jLabel1");
        add(jLabel1);

        jButton3.setBackground(new java.awt.Color(240, 240, 240));
        jButton3.setText("jButton3");
        add(jButton3);

        jLabel2.setText("jLabel2");
        add(jLabel2);

        jLabel3.setText("jLabel3");
        add(jLabel3);

        jLabel4.setText("jLabel4");
        add(jLabel4);

        jButton6.setBackground(new java.awt.Color(240, 240, 240));
        jButton6.setText("jButton6");
        add(jButton6);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
